
* Supported Features

** Convert .flac extensions in playlists to m4a
#+begin_src sh :tangle yes
--flac_ext_to_alac # Default = True
#+end_src

** Convert Windows paths to Posix (Linux/OSX) paths
#+begin_src sh :tangle yes
--windows_to_posix # Default = False
#+end_src

* Run
** Write to output dir
#+begin_src sh :tangle yes
python foo_tunes.py -i=/Volumes/drive/playlists/windows --verbose -o=temp
#+end_src

#+begin_src sh :tangle yes
./foo_tunes.py -i=/Volumes/bebe/playlists/windows --verbose -o=temp2
#+end_src

** To overwrite files
#+begin_src sh :tangle yes
./foo_tunes.py -i=/Volumes/bebe/playlists/windows --verbose
#+end_src

* Test
#+begin_src sh :tangle yes
python -m foo_tunes_test
#+end_src

* Random Foobar Notes
** Changing Music Directory Path
For example, say the original media library was on J:/ and the new media library
is on X:/, you can Go to File -> Preferences -> Music Library -> Music Folders
-> Add -> Add new Path.

Let Foobar2000 populate all the music files from the new path. There will be
duplicates until this whole process is finished. Once Foobar's music folder
status is 'Monitoring', Use Playlist Revive.

Go to each playlist -> Edit -> Revive Dead Items.

This should point all the paths to the new path at the new music directory
location.
** Rename Pattern
#+begin_src text :tangle yes
%album artist% - %album%[ '('%date%')'] '['$if($strstr(%codec%,FLAC),FLAC,$if($strstr(%__codec_profile%,CBR),%__bitrate%,V0))']'/%tracknumber%. [%artist% - ]%title%
#+end_src
** Directory Style
#+begin_src text :tangle yes
%genre%/%artist%/%album%/%tracknumber% %title%
#+end_src
** Exporting all Playlists
#+begin_src text :tangle yes
View -> Playlist Manager -> Right Click -> Save all Playlists -> m3u8

There are a few entries for Playlist Manager, choose the last one.

Save to: e.g. X:\playlists\windows
#+end_src
* Workflow
Make all music directories follow: [[*Directory Style][Directory Style]].
